M48
; DRILL file {KiCad 9.0.2-9.0.2-0~ubuntu22.04.1} date 2025-10-14T18:04:42+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-14T18:04:42+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2-9.0.2-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X131.17Y-75.15
X164.19Y-127.22
X179.43Y-76.42
M30
